### PR TITLE
removed deprecation attribute for get_*

### PR DESCRIPTION
**Pull request by dmalan**
CC @glennholloway @kzidane

### CODE REVIEW

**Comment by kzidane** [comment]
so this is supposed to be temporary until updating the Makefiles to include `-Wno-deprecated-declarations`?

**Comment by kzidane** [comment]
or actually may be better have the Makefile use CFLAGS?

**Comment by dmalan** [comment]
Some students already have Makefiles in their accounts, which we can't
update, so seems best to wait until CS50x 2017 (in January) to deprecate
the functions officially.

**Comment by dmalan** [comment]
@glennholloway merged!

**Pull request merged**
