### PR TITLE
Add testing infrastructure

### PR DESCRIPTION
**Pull request by crossroads1112**
This is not meant to be merged just yet. Rather, I wanted to get input on this testing methodology so I know whether or not I should continue writing tests.

This PR adds a program called `test_driver` under the `tests` directory. `test_driver` contains a list of tests to be run. Each test should have its own subdirectory within `tests` directory containing its executable and an input file. `test_driver` will then run the test executable in a child process with the input file's descriptor as stdin. `test_driver` will abort at the first failed test.

`test_driver.h` defines a macro called `Assertf` which can be used by the tests (though it does not need to be) to make an assertion with a custom error message (using `eprintf`).

The benefit of this model is its modularity. Adding a test is as simple as adding its name to the `tests` array in `test_driver.c` and adding it to the Makefile. If this model is accepted, it would be fairly easy to have the Makefile simply search for any subdirectories of `tests` (perhaps that follow a certain naming convention) and have `test_driver` do the same meaning the only step required to add a new test would be running `make`.

### CODE REVIEW

**Comment by dmalan** [comment]
I like. Would be handy if `main` simply iterates over some directory with the test files, rather than having to add them to the global array.

Can you envision a type of test that also checks `stdout`, not just return values, a la `expect`? In particular, we'd want to check for `"Retry: ` upon provision of invalid inputs. (Ideally, we'd check only return values, but the library deliberately spins until users provide inputs as expected.)

**Comment by crossroads1112** [comment]
>  Would be handy if main simply iterates over some directory with the test files

Sorry for being unclear but that is what I was attempting to say in the last paragraph of my PR.

> In particular, we'd want to check for "Retry: upon provision of invalid inputs.

Would having a test file with multiple invalid inputs followed by a valid input work?

    // get_int/get_int.txt
    a
    124c
        1
    10

    //get_int/get_int.c
    int main(void)
    {
        int i = get_int();
        Assertf(i == 10, "Expected 10, got %d", i);
    }

**Comment by dmalan** [comment]
@crossroads1112 not opposed, though for precision's sake, could we redirect `stdout` and `strcmp` it to ensure we're indeed seeing `"Retry: "` as expected?

**Comment by crossroads1112** [comment]
@dmalan Yes that should be possible via a pipe between the child and the parent. The question is where the string `strcmp` is comparing should reside. Should there be an additional output file in the test's subdirectory?

**Comment by dmalan** [comment]
If we need separate input files feels reasonable to have corresponding
output files. But realistically all of our tests will be small, so I'd just
as soon confine test inputs and outputs to the .c files as strings. Easier
to see line endings that way too.

**Comment by crossroads1112** [comment]
The problem with having the test inputs in the `.c` file is that I do not know of a way to replace `stdin` with a local buffer (without writing it to a file first). Obviously you could repeatedly call `ungetc` for every character in the buffer but the C standard only guarantees one successful call to `ungetc` which makes me a bit nervous.

**Comment by crossroads1112** [comment]
093d5d7 allows test_driver to check the output of the tests. It checks for `testname/output.txt` and if it exists, uses `strcmp` to compare the child's output. If `output.txt` does not exists it asks the user if the output is correct and if it is, writes it to `output.txt`

**Comment by crossroads1112** [comment]
Closing this PR and reopening with changes squashed to one commit

**Pull request closed without merging**
